#pragma once

enum AreaBytesJAN {
    AB_JAN22_ZiplineNpc1                = AreaByte(0),
    AB_JAN22_ZiplineNpc2                = AreaByte(1),
    AB_JAN13_LargeGeyserState           = AreaByte(2),
    AB_JAN13_LastPuzzleProgress         = AreaByte(3),
    AB_JAN_Unused_4                     = AreaByte(4),
    AB_JAN_Unused_5                     = AreaByte(5),
    AB_JAN_Unused_6                     = AreaByte(6),
    AB_JAN_Unused_7                     = AreaByte(7),
    AB_JAN_Unused_8                     = AreaByte(8),
    AB_JAN_Unused_9                     = AreaByte(9),
    AB_JAN_Unused_A                     = AreaByte(10),
    AB_JAN_Unused_B                     = AreaByte(11),
    AB_JAN_Unused_C                     = AreaByte(12),
    AB_JAN_Unused_D                     = AreaByte(13),
    AB_JAN_Unused_E                     = AreaByte(14),
    AB_JAN_Unused_F                     = AreaByte(15),
};

enum AreaFlagsJAN {
    AF_JAN_SavedCurrentYoshiKid         = AreaFlag(2),
    AF_JAN_PlayingRaphaelVariant        = AreaFlag(3),
    AF_JAN02_RaphaelComment             = AreaFlag(4),
    AF_JAN02_MetCouncillor              = AreaFlag(5),
    AF_JAN03_KoloradoLocalsHint         = AreaFlag(6),
    AF_JAN03_MetSushieDialogue          = AreaFlag(7),
    AF_JAN04_IgnoreSushieTreeHit        = AreaFlag(8),
    AF_JAN01_KoloradoShouting           = AreaFlag(9),
    AF_JAN22_PauseSpearGuyAttack        = AreaFlag(10),
    AF_JAN22_MisstarReleasedParty       = AreaFlag(11),
    AF_JAN22_MisstarReleasedKolorado    = AreaFlag(12),
    AF_JAN00_TreeDrop1                  = AreaFlag(13),
    AF_JAN01_TreeDrop2                  = AreaFlag(14),
    AF_JAN01_TreeDrop3                  = AreaFlag(15),
    AF_JAN01_TreeDrop4                  = AreaFlag(16),
    AF_JAN01_TreeDrop5                  = AreaFlag(17),
    AF_JAN01_TreeDrop6                  = AreaFlag(18),
    AF_JAN01_TreeDrop7                  = AreaFlag(19),
    AF_JAN02_TreeDrop2                  = AreaFlag(20),
    AF_JAN02_TreeDrop3                  = AreaFlag(21),

    AF_JAN03_TreeDrop1                  = AreaFlag(23),
};
