#!/usr/bin/env python3

import os
import subprocess
import shutil

ROM = "ver/current/build/papermario.z64"
EMULATOR_PATHS = [
    "cen64",
    "ares",
    "mupen64plus",
    "retroarch",
    "Project64",
]
emulator = None

for command in EMULATOR_PATHS:
    if shutil.which(command) is not None:
        emulator = command
        break

    # WSl compat
    command += ".exe"
    if shutil.which(command) is not None:
        emulator = command
        break

def windows_path(path):
    return subprocess.check_output(["wslpath", "-w", path]).decode().strip()

def main():
    if os.system(f"ninja {ROM}") != 0:
        print("error: build failed")
        return

    wsl = os.name == "posix"
    rom = windows_path(ROM) if wsl else ROM

    if emulator is not None:
        subprocess.run([emulator, rom])
    else:
        print("error: no emulator found")
        if wsl:
            print("  hint: add an emulator to your PATH")

if __name__ == "__main__":
    main()
