#include "kkj_00.h"

#include "world/common/npc/ToadGuard/idle.inc.c"
#include "world/common/npc/ToadMinister/idle.inc.c"
#include "world/common/npc/Toadette/idle.inc.c"
#include "world/common/npc/ShiverToad/idle.inc.c"
#include "world/common/npc/Luigi/idle.inc.c"
#include "world/common/npc/Toad/patrol.inc.c"
#include "world/common/npc/Toad/idle.inc.c"
#include "world/common/npc/Penguin/idle.inc.c"
#include "world/common/npc/RussT/idle.inc.c"
#include "world/common/npc/Peach/idle.inc.c"
#include "world/common/npc/Dummy/idle.inc.c"
#include "world/common/npc/Lakilulu/idle.inc.c"
#include "world/common/npc/TayceT/idle.inc.c"
