#pragma once
#include "base.h"

extern MobileAISettings AISettings_FlyingMagikoopa_Wander;
extern EvtScript EVS_NpcAI_FlyingMagikoopa_Wander;
extern EvtScript EVS_NpcDefeat_FlyingMagikoopa;
extern NpcSettings NpcSettings_FlyingMagikoopa_Wander;
extern EvtScript EVS_NpcCreate_FlyingMagikoopa_AltHitbox;
extern EvtScript EVS_NpcCreate_FlyingMagikoopa_Hitbox;
extern EvtScript EVS_NpcAI_FlyingMagikoopa_Hitbox;
extern EvtScript EVS_NpcHit_FlyingMagikoopa_Hitbox;
extern EvtScript EVS_NpcDefeat_FlyingMagikoopa_Hitbox;
extern NpcSettings NpcSettings_FlyingMagikoopa_AltHitbox;
extern NpcSettings NpcSettings_FlyingMagikoopa_Hitbox;
