#pragma once
#include "base.h"

extern MobileAISettings AISettings_Magikoopa_Wander;
extern EvtScript EVS_NpcAI_Magikoopa_Wander;
extern EvtScript EVS_NpcHit_Magikoopa;
extern EvtScript EVS_NpcDefeat_Magikoopa;
extern NpcSettings NpcSettings_Magikoopa_Wander;
extern EvtScript EVS_NpcCreate_Magikoopa_GroundHitbox;
extern EvtScript EVS_NpcCreate_Magikoopa_FlyingHitbox;
extern EvtScript EVS_NpcAI_Magikoopa_Hitbox;
extern EvtScript EVS_NpcHit_Magikoopa_Hitbox;
extern EvtScript EVS_NpcDefeat_Magikoopa_Hitbox;
extern NpcSettings NpcSettings_Magikoopa_GroundHitbox;
extern NpcSettings NpcSettings_Magikoopa_FlyingHitbox;
