#pragma once
#include "base.h"

extern EvtScript EVS_NpcCreate_MontyMole_GroundAmbush;
extern EvtScript EVS_NpcCreate_MontyMole_GroundAmbush_Hole;
extern MobileAISettings AISettings_MontyMole_GroundAmbush;
extern EvtScript EVS_NpcAI_MontyMole_GroundAmbush;
extern NpcSettings NpcSettings_MontyMole_GroundAmbush;
extern NpcSettings NpcSettings_MontyMole_GroundAmbush_Hole;
