#pragma once
#include "base.h"

extern EvtScript EVS_NpcCreate_MontyMole_WallAmbush;
extern EvtScript EVS_NpcCreate_MontyMole_WallAmbush_Hole;
extern MobileAISettings AISettings_MontyMole_WallAmbush;
extern EvtScript EVS_NpcAI_MontyMole_WallAmbush;
extern NpcSettings NpcSettings_MontyMole_WallAmbush;
extern NpcSettings NpcSettings_MontyMole_WallAmbush_Hole;
