#pragma once
#include "base.h"

extern EvtScript EVS_NpcDefeat_HammerBros_Hammer;
extern MobileAISettings AISettings_HammerBros;
extern EvtScript EVS_NpcAI_HammerBros;
extern NpcSettings NpcSettings_HammerBros_Wander;
extern MobileAISettings AISettings_HammerBros_Hammer;
extern EvtScript EVS_NpcAI_HammerBros_Hammer;
extern EvtScript EVS_NoAI_HammerBros_Hammer;
extern EvtScript EVS_NpcHit_HammerBros_Hammer;
extern NpcSettings NpcSettings_HammerBros_Hammer;
